### ISSUE TITLE
Sharing data for analysis

### ISSUE THREAD

**Issue by FavioVazquez** [harishpuvvada/BitCoin-Value-Predictor#11]
Hi. In your preparation and analysis notebooks you have some files that are not backed in the repo. 

It could be great if you could share them too so the project can be fully reproducible. 

Thanks :).

**Comment by harishpuvvada** [comment]
Hi,
Are you asking for the data (.csv) files ?
If so, they are too big to upload here (around 500 mb)

**Comment by harishpuvvada** [comment]
shared data on drop box

**Comment by FavioVazquez** [comment]
Thanks a lot @harishpuvvada !!

**Comment by nikhil-pandita** [comment]
May I also get the drop box link? Thank you.

**Comment by YingLAIlive** [comment]
Hi, Favio. It's a great job! And could you share your code with me? I wanna have a deeper look into it. Thanks!

**Comment by YingLAIlive** [comment]
Hi, harishpuvvada. It's a great job! And could you share your code with me? I wanna have a deeper look into it. Thanks!

**Comment by harishpuvvada** [comment]
> May I also get the drop box link? Thank you.

https://www.dropbox.com/s/oy5zcf4aiorr0dr/Archive.zip?dl=0
